# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leroy_pointlcoud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16leroy_pointlcoud.proto\x12\tpcl_proto\"7\n\tPointXYZI\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01i\x18\x04 \x01(\x02\"7\n\tPointRGBA\x12\t\n\x01r\x18\x01 \x01(\x02\x12\t\n\x01g\x18\x02 \x01(\x02\x12\t\n\x01\x62\x18\x03 \x01(\x02\x12\t\n\x01\x61\x18\x04 \x01(\x02\"B\n\nPointCloud\x12\x0e\n\x06header\x18\x01 \x01(\t\x12$\n\x06points\x18\x02 \x03(\x0b\x32\x14.pcl_proto.PointXYZI\"\x83\x01\n\x11OntologyLanePoint\x12#\n\x05point\x18\x01 \x01(\x0b\x32\x14.pcl_proto.PointXYZI\x12\x16\n\x0elane_direction\x18\x03 \x01(\x02\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x11\n\tbay_track\x18\x05 \x01(\x05\x12\x10\n\x08overtake\x18\x06 \x01(\x05\"V\n\x16OntologyLanePointCloud\x12\x0e\n\x06header\x18\x01 \x01(\t\x12,\n\x06points\x18\x02 \x03(\x0b\x32\x1c.pcl_proto.OntologyLanePoint\"\xb2\x01\n\x18OntologyRoadNetworkPoint\x12#\n\x05point\x18\x01 \x01(\x0b\x32\x14.pcl_proto.PointXYZI\x12\x11\n\tdirection\x18\x02 \x01(\x02\x12\x0f\n\x07weights\x18\x03 \x01(\x05\x12\x12\n\nwide_turns\x18\x04 \x01(\x05\x12\x13\n\x0blane_change\x18\x05 \x01(\x05\x12\r\n\x05\x65xits\x18\x06 \x01(\x05\x12\x15\n\rexit_velocity\x18\x07 \x01(\x02\"d\n\x1dOntologyRoadNetworkPointCloud\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x33\n\x06points\x18\x02 \x03(\x0b\x32#.pcl_proto.OntologyRoadNetworkPoint\"\xca\x01\n\x06Marker\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\n\n\x02ns\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x0c\n\x04type\x18\x05 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\x05\x12\"\n\x04pose\x18\x07 \x01(\x0b\x32\x14.pcl_proto.PointXYZI\x12#\n\x05scale\x18\x08 \x01(\x0b\x32\x14.pcl_proto.PointXYZI\x12#\n\x05\x63olor\x18\t \x01(\x0b\x32\x14.pcl_proto.PointRGBA\"1\n\x0bMarkerArray\x12\"\n\x07markers\x18\x01 \x03(\x0b\x32\x11.pcl_proto.Markerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leroy_pointlcoud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTXYZI._serialized_start=37
  _POINTXYZI._serialized_end=92
  _POINTRGBA._serialized_start=94
  _POINTRGBA._serialized_end=149
  _POINTCLOUD._serialized_start=151
  _POINTCLOUD._serialized_end=217
  _ONTOLOGYLANEPOINT._serialized_start=220
  _ONTOLOGYLANEPOINT._serialized_end=351
  _ONTOLOGYLANEPOINTCLOUD._serialized_start=353
  _ONTOLOGYLANEPOINTCLOUD._serialized_end=439
  _ONTOLOGYROADNETWORKPOINT._serialized_start=442
  _ONTOLOGYROADNETWORKPOINT._serialized_end=620
  _ONTOLOGYROADNETWORKPOINTCLOUD._serialized_start=622
  _ONTOLOGYROADNETWORKPOINTCLOUD._serialized_end=722
  _MARKER._serialized_start=725
  _MARKER._serialized_end=927
  _MARKERARRAY._serialized_start=929
  _MARKERARRAY._serialized_end=978
# @@protoc_insertion_point(module_scope)
